name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...
      
    - name: Build dictionaries
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        wget https://dumps.wikimedia.org/enwiktionary/latest/enwiktionary-latest-pages-articles.xml.bz2
        bzip2 -d enwiktionary-latest-pages-articles.xml.bz2
        ./go-wikitionary-parse -file enwiktionary-latest-pages-articles.xml -threads 20 -database en_minimal.db -exclude_cat "Proper noun" -min_letters 3 -max_defs 1 -rm_accents -max_etys 1 -single_words -minimal
        tar -czvf en_minimal.tar.gz en_minimal.db
        tar -czvf go-wikitionary-parse-linux-amd64.tar.gz go-wikitionary-parse
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          go-wikitionary-parse-linux-amd64.tar.gz
          en_minimal.tar.gz
